# CMake generated Testfile for 
# Source directory: C:/MCP/core/tests
# Build directory: C:/MCP/core/cli/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("core" "C:/MCP/core/cli/tests/Debug/test_core.exe")
  set_tests_properties("core" PROPERTIES  _BACKTRACE_TRIPLES "C:/MCP/core/tests/CMakeLists.txt;13;add_test;C:/MCP/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("core" "C:/MCP/core/cli/tests/Release/test_core.exe")
  set_tests_properties("core" PROPERTIES  _BACKTRACE_TRIPLES "C:/MCP/core/tests/CMakeLists.txt;13;add_test;C:/MCP/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("core" "C:/MCP/core/cli/tests/MinSizeRel/test_core.exe")
  set_tests_properties("core" PROPERTIES  _BACKTRACE_TRIPLES "C:/MCP/core/tests/CMakeLists.txt;13;add_test;C:/MCP/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("core" "C:/MCP/core/cli/tests/RelWithDebInfo/test_core.exe")
  set_tests_properties("core" PROPERTIES  _BACKTRACE_TRIPLES "C:/MCP/core/tests/CMakeLists.txt;13;add_test;C:/MCP/core/tests/CMakeLists.txt;0;")
else()
  add_test("core" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("stdlib" "C:/MCP/core/cli/tests/Debug/test_stdlib.exe")
  set_tests_properties("stdlib" PROPERTIES  _BACKTRACE_TRIPLES "C:/MCP/core/tests/CMakeLists.txt;14;add_test;C:/MCP/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("stdlib" "C:/MCP/core/cli/tests/Release/test_stdlib.exe")
  set_tests_properties("stdlib" PROPERTIES  _BACKTRACE_TRIPLES "C:/MCP/core/tests/CMakeLists.txt;14;add_test;C:/MCP/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("stdlib" "C:/MCP/core/cli/tests/MinSizeRel/test_stdlib.exe")
  set_tests_properties("stdlib" PROPERTIES  _BACKTRACE_TRIPLES "C:/MCP/core/tests/CMakeLists.txt;14;add_test;C:/MCP/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("stdlib" "C:/MCP/core/cli/tests/RelWithDebInfo/test_stdlib.exe")
  set_tests_properties("stdlib" PROPERTIES  _BACKTRACE_TRIPLES "C:/MCP/core/tests/CMakeLists.txt;14;add_test;C:/MCP/core/tests/CMakeLists.txt;0;")
else()
  add_test("stdlib" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("phase5x" "C:/MCP/core/cli/tests/Debug/test_phase5x.exe")
  set_tests_properties("phase5x" PROPERTIES  _BACKTRACE_TRIPLES "C:/MCP/core/tests/CMakeLists.txt;15;add_test;C:/MCP/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("phase5x" "C:/MCP/core/cli/tests/Release/test_phase5x.exe")
  set_tests_properties("phase5x" PROPERTIES  _BACKTRACE_TRIPLES "C:/MCP/core/tests/CMakeLists.txt;15;add_test;C:/MCP/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("phase5x" "C:/MCP/core/cli/tests/MinSizeRel/test_phase5x.exe")
  set_tests_properties("phase5x" PROPERTIES  _BACKTRACE_TRIPLES "C:/MCP/core/tests/CMakeLists.txt;15;add_test;C:/MCP/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("phase5x" "C:/MCP/core/cli/tests/RelWithDebInfo/test_phase5x.exe")
  set_tests_properties("phase5x" PROPERTIES  _BACKTRACE_TRIPLES "C:/MCP/core/tests/CMakeLists.txt;15;add_test;C:/MCP/core/tests/CMakeLists.txt;0;")
else()
  add_test("phase5x" NOT_AVAILABLE)
endif()
