import { logger } from "../utils/logger";
import { db } from "../fisp/database";
import { createInstallationToken } from "../github/tokens";

export async function openPrForProposal(proposal: any, path: string, content: string) {
  let token = process.env.GITHUB_TOKEN;
  const owner = proposal.targetRepo ? proposal.targetRepo.split('/')[0] : process.env.GITHUB_OWNER;
  const repo = proposal.targetRepo ? proposal.targetRepo.split('/')[1] : process.env.GITHUB_REPO;

  if (!token) {
    try {
      const inst = db.prepare('SELECT installation_id FROM github_installations LIMIT 1').get() as any;
      if (inst?.installation_id) {
        token = await createInstallationToken(inst.installation_id);
      }
    } catch (e) {
      logger.error("Failed to generate GitHub App token:", e);
    }
  }

  if (!token || !owner || !repo) {
    logger.info("GitHub credentials missing. PR creation skipped.");
    return null;
  }

  try {
    const branchName = `proposal/${proposal.id}-${(proposal.name || 'ext').toLowerCase().replace(/\s+/g, '-')}`;
    
    // 1. Get default branch SHA
    const repoRes = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
      headers: { Authorization: `token ${token}` }
    });
    const repoData = await repoRes.json();
    const defaultBranch = repoData.default_branch || 'main';

    const refRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${defaultBranch}`, {
      headers: { Authorization: `token ${token}` }
    });
    const refData = await refRes.json();
    const baseSha = refData.object.sha;

    // 2. Create new branch
    await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`, {
      method: "POST",
      headers: { Authorization: `token ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha })
    });

    // 3. Create Blob
    const blobRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/blobs`, {
      method: "POST",
      headers: { Authorization: `token ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({ content, encoding: "utf-8" })
    });
    const blobData = await blobRes.json();

    // 4. Create Tree
    const treeRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/trees`, {
      method: "POST",
      headers: { Authorization: `token ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        base_tree: baseSha,
        tree: [{ path, mode: "100644", type: "blob", sha: blobData.sha }]
      })
    });
    const treeData = await treeRes.json();

    // 5. Create Commit
    const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits`, {
      method: "POST",
      headers: { Authorization: `token ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        message: `SDOA Auto-Extraction: ${proposal.name}`,
        tree: treeData.sha,
        parents: [baseSha]
      })
    });
    const commitData = await commitRes.json();

    // 6. Update Ref
    await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branchName}`, {
      method: "PATCH",
      headers: { Authorization: `token ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({ sha: commitData.sha })
    });

    // 7. Create PR
    const prRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
      method: "POST",
      headers: { Authorization: `token ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        title: `Extract ${proposal.type}: ${proposal.name}`,
        head: branchName,
        base: defaultBranch,
        body: `Automated PR generated by SDOA Engine.\n\nProposal ID: ${proposal.id}`
      })
    });
    const prData = await prRes.json();
    return prData.html_url || null;
  } catch (err: any) {
    logger.error("Failed to create PR:", err);
    return null;
  }
}
