const fs = require('fs');
const path = require('path');

async function generateAI(content) {
  try {
    const prompt = `Analyze this code and return ONLY a valid JSON object representing its SDOA manifest properties. Do not use markdown blocks, just return raw JSON.
The JSON must have exactly three keys: "capabilities" (an array of strings representing functions/classes exported), "dependencies" (an array of strings representing imports/requires), and "docs" (a concise 1-sentence description of what this code does).

Code to analyze:
${content}

Return ONLY valid JSON.`;

    const res = await fetch('http://127.0.0.1:11434/api/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'llama3.2',
        prompt: prompt,
        stream: false,
        format: 'json'
      })
    });
    
    if (!res.ok) return null;
    const data = await res.json();
    return JSON.parse(data.response);
  } catch (e) {
    return null;
  }
}

function walk(d) {
  let res = [];
  const files = fs.readdirSync(d);
  for(const f of files) {
    if (['node_modules', '.git', 'dist'].includes(f)) continue;
    const p = path.join(d, f);
    if (fs.statSync(p).isDirectory()) {
      res = res.concat(walk(p));
    } else if (/\.(ts|js)$/.test(f)) {
      res.push(p);
    }
  }
  return res;
}

async function run() {
  const files = walk(process.cwd());
  let processed = 0;
  let failed = 0;

  for (const file of files) {
    let content = fs.readFileSync(file, 'utf8');
    
    // Check if it has a MANIFEST block at all
    if (!content.includes('MANIFEST')) continue;
    // Check if it has the default "via static analysis" docs or "stability" without custom docs
    if (!content.includes('Auto-generated enriched SDOA manifest via static analysis') && 
        !(content.includes('optimization: { priority: "stability" }') && !content.includes('capabilities:'))) {
        continue; // Already custom/enriched
    }

    const filename = path.basename(file);
    const ext = path.extname(filename);
    const isJS = ext === '.js';
    
    console.log(`Asking Ollama to analyze: ${file}...`);
    const aiData = await generateAI(content);
    
    if (!aiData) {
      console.log(`Failed to get valid JSON from Ollama for ${file}`);
      failed++;
      continue;
    }

    const capStr = aiData.capabilities && aiData.capabilities.length > 0 
      ? `[\n    "${aiData.capabilities.join('",\n    "')}"\n  ]` 
      : `[]`;
    const depStr = aiData.dependencies && aiData.dependencies.length > 0 
      ? `[\n    "${aiData.dependencies.join('",\n    "')}"\n  ]` 
      : `[]`;
    const docsStr = aiData.docs ? `"${aiData.docs.replace(/"/g, "'")}"` : `"Auto-generated by Llama3.2"`;
    
    const isExported = content.includes('export const MANIFEST =');
    const declaration = isExported ? 'export const MANIFEST =' : 'const MANIFEST =';
    
    const newManifest = `${declaration} {
  id: "${filename}",
  type: "module",
  layer: 4,
  runtime: "${isJS ? 'JavaScript' : 'TypeScript'}",
  version: "1.0.0",
  operationalRole: "infrastructure",
  optimization: { priority: "stability" },
  capabilities: ${capStr},
  dependencies: ${depStr},
  docs: ${docsStr}
};`;

    const replaceRegex = /(?:export const MANIFEST =|const MANIFEST =) \{[\s\S]*?optimization: \{ priority: "stability" \}[\s\S]*?\};/;
    
    if (replaceRegex.test(content)) {
      content = content.replace(replaceRegex, newManifest);
      fs.writeFileSync(file, content, 'utf8');
      processed++;
      console.log(`Successfully AI-enriched MANIFEST in: ${file}`);
    } else {
      console.log(`Regex mismatch for MANIFEST in: ${file}`);
      failed++;
    }
  }

  console.log(`\nComplete! Processed: ${processed}, Failed: ${failed}`);
}

run();
