sonar.projectKey=sdoa-mcp-extension
sonar.projectName=sdoa-mcp-extension
sonar.projectVersion=1.0.0
sonar.sources=public,adapters
sonar.tests=

sonar.language=js,ts
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=squ_YfiC3M17PSCUCzFHdp67Ied6ee1nR1DqSfCy
sonar.exclusions=**/node_modules/**,**/dist/**,**/temp/**,**/*.txt
