name: Publish SDOA MCP Extension

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build & Package Extension
        run: npm run release

      - name: Publish to Open VSX Registry
        run: npx ovsx publish *.vsix -p $OVSX_PAT
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}

      - name: Publish to VS Code Marketplace
        run: npx vsce publish --packagePath *.vsix -p $VSCE_PAT
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
